### ISSUE TITLE
Missed mobile menu to login, Missed operator three dots menù in a ticket

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/support-center-bundle#101]
# Bug report

### Issue Description

Customer side
Ticket seing from a mobile miss the right mobile menù, the menù is present but not visible.
If the user click on the right a menù with also the login and contact button is showed but in the open source there is no visible button on top right.

Operator side:
If a ticket is opened no three dots menù for delete the ticket and do other action are showed, in mobile.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Issue Fixed.

**Comment by PeopleInside** [comment]
Issue is not fixed.

**Comment by PeopleInside** [comment]
Thank you for the fix
