### ISSUE TITLE
Footer cookie link issue on mobile

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/support-center-bundle#102]
# Bug report

If you click on cookie consent link on the footer from a mobile device the pop is not well showed

![SharedScreenshot](https://user-images.githubusercontent.com/5006150/87452882-0b4c3780-c602-11ea-8d5d-6a51bb33cd02.jpg)

**Comment by papnoisanjeev** [comment]
@PeopleInside 
Fixed in latest release.
