### ISSUE TITLE
Doctrine Entities Mapping error on KnowledgebaseWebsite#website

### ISSUE THREAD

**Issue by quazardous** [uvdesk/support-center-bundle#103]
**Description**  
WebProfile reports a Doctrine Entities Mapping error on `KnowledgebaseWebsite#website`

**How to reproduce**  
install current community-skeleton
signin member area
look in the webprofiler

**Possible Solution**  

**Additional context**  

Error
```

Webkul\UVDesk\SupportCenterBundle\Entity\KnowledgebaseWebsite

The  association  Webkul\UVDesk\SupportCenterBundle\Entity\KnowledgebaseWebsite#website  refers to the inverse side field  Webkul\UVDesk\CoreFrameworkBundle\Entity\Website#website which does not  exist.

```

Versions
```
uvdesk/api-bundle                         v1.0.2  Easily integrate with your community helpdesk system using the uvdesk api bundle.
uvdesk/automation-bundle                  v1.0.7  UVDesk Community Helpdesk Automations Bundle
uvdesk/composer-plugin                    v1.0.1  Generic purpose composer plugin to auto-configure your packages
uvdesk/core-framework                     v1.0.12 UVDesk Community Helpdesk Core Framework Bundle
uvdesk/extension-framework                v1.0.4  UVDesk Community Helpdesk Extension Framework Bundle
uvdesk/mailbox-component                  v1.0.9  The Mailbox component provides tools that allows your helpdesk to process tickets from multiple email sources.
uvdesk/support-center-bundle              v1.0.8  UVDesk Community Helpdesk Customer Support Center Bundle
```

**Comment by papnoisanjeev** [comment]
@quazardous 

We have updated the Entity now will not see this error in next release.
Also you can correct it by some change in your project by copy and paste this file from [here](https://github.com/uvdesk/support-center-bundle/blob/master/Entity/KnowledgebaseWebsite.php).

Check changes [here](https://github.com/uvdesk/support-center-bundle/commit/cf5aeda6334954dd2b7f348a3b5db3b98f78a322).

It will reflect in next release.

**Comment by vaishaliwebkul** [comment]
@quazardous 
this is fixed now in the master so closing this.
We will soon release our next release.
