### ISSUE TITLE
Getting exception while viewing categories/folder/articles at backend

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/support-center-bundle#107]
**Description**  
Getting an exception while viewing categories/folder/articles at the backend

**Precondition** 
Version- master

**How to reproduce**  

>>step-1 Login as admin account
>>step2- Open either category, folder, article list

**Additional context**  

![Screenshot_35](https://user-images.githubusercontent.com/43210406/95837126-dd3fd600-0d5d-11eb-9732-d9e4a93f003e.png)

![Screenshot_36](https://user-images.githubusercontent.com/43210406/95837967-d9f91a00-0d5e-11eb-8662-5a129fc7132e.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed in master.
