### ISSUE TITLE
contact us form is not working

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/support-center-bundle#108]
**Description**  
contact us form is not working

**Preconditions**
Version- master

**How to reproduce**  
- At helpdesk front page, click on contact us button to create ticket

**Additional context**  
![Screenshot_44](https://user-images.githubusercontent.com/43210406/95855531-30258780-0d76-11eb-95e8-ae435464d363.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed in master branch.
