### ISSUE TITLE
customer panel showing error

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/support-center-bundle#110]
**Precondition**
Version- master

**How to reproduce**  
- login with customer account

**Additional context**  
![Screenshot_59](https://user-images.githubusercontent.com/43210406/96137826-c0043680-0f1a-11eb-9dd9-1ecdf7547ec7.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed in master.
