### ISSUE TITLE
video attachment in article is not working

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/support-center-bundle#112]
**Description**  
video link is always removed from the article

**How to reproduce**  
- go to the article
- In tinymc editor, click on add media and provide video link

**Additional context**  
link is removed and unable to attach media
![Screenshot_65](https://user-images.githubusercontent.com/43210406/96255998-7c223780-0fd5-11eb-8df3-98cd0a303f73.png)

**Comment by PeopleInside** [comment]
From the browser developer console I see functions deprecated. Maybe some issue with old components or code that need to be updated.

**Comment by leonpidgeon** [comment]
I had the same issue as it would not allow videos to be embedded from youtube. We had to link instead to the video file and that worked fine. Everytime we tried with youtube the code was removed automatically.

**Comment by vaishaliwebkul** [comment]
@leonpidgeon 
No worry! this has been fixed in UVdesk master branch.
you can make these changes in your project https://github.com/uvdesk/support-center-bundle/commit/0a077d12473f6374961a19d14b3117755899a81d

don't forget to flush the cache using **php bin/console c:c**
