### ISSUE TITLE
add image upload icon in article editor

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/support-center-bundle#116]
**Description**  
In the article section, an option to upload an image from the local system is not available.

![Screenshot_221](https://user-images.githubusercontent.com/43210406/104993598-17013680-5a49-11eb-81a6-409e355ed6ea.png)

**expected result**
![Screenshot_222](https://user-images.githubusercontent.com/43210406/104993670-35ffc880-5a49-11eb-943e-2c95f4f5ff4b.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Added the external image add option and IFrame support in editor for Article section.
https://github.com/uvdesk/support-center-bundle/commit/23137697a3e3b54f22d205c31014c22a754b81e1

**Comment by vaishaliwebkul** [comment]
@papnoisanjeev 
external image option is already added here https://prnt.sc/y05cu9.
issue is raised for adding local images.
