### ISSUE TITLE
[Feature request] Support HTML in Knowledgebase

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/support-center-bundle#117]
**Description**  

Actually seems there is no way to insert HTML elements on the Knowledge base

Add support for HTML in the editor or articles cannot have HTML element.

**Comment by vaishaliwebkul** [comment]
@PeopleInside 
the donation button is a JS code that's why it's not supported on the knowledge.
If you want to implement this for knowledge than you can add this in **advance** section under branding as shown here https://prnt.sc/xcjkhk , so that this will be added in the knowledgebase

![Screenshot_228](https://user-images.githubusercontent.com/43210406/105315504-6e3c0e00-5be5-11eb-91f5-fa6f8a6cc49e.png)

**Comment by PeopleInside** [comment]
I don't wanna add on top on every page just in one article.

**Comment by PeopleInside** [comment]
@vaishaliwebkul I sent a message on Skype about the editor that is present when operator reply to a ticket.
In this GitHub topic we discuss the editor of Knowledge base but I want open another issue where there is too basic editor in operator interface when reply to a ticket.

The basic editor doesn't allow to insert hyperlink or images and this is very bad. Where I can open this issue?

**Comment by papnoisanjeev** [comment]
@PeopleInside  @vaishaliwebkul 

We have added some more option on operator side when reply to a ticket.
**hyperlink**, **Spellcheck**, adding a **image** by a **external link**, **source code** option added into editor.

For now you can add this into your project.
Locate path:
**vendor/uvdesk/core-framework/Resources/views/Templates/tinyMCE.html.twig**

Open your **tinyMCE.html.twig** file and replace it from [here](https://github.com/uvdesk/core-framework/blob/master/Resources/views/Templates/tinyMCE.html.twig).

It will also reflect from next release.

**Comment by PeopleInside** [comment]
For me seems doesn't work the fix.
I made it but still not showing on ticket reply the new editor.
I have a cron that clear the cache every 5 minutes so changes has been done from me but is not working. Are you sure the patch work?

**Comment by papnoisanjeev** [comment]
@PeopleInside 

We have already tested it so we have shared screenshot with you for the same.
Please share the steps and where you have made changes.

Is you are getting any error on console sometime copy and paste may miss something in that file or not saved changes.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Tested again with a **new project** and replace **tinyMCE.html.twig** (vendor/uvdesk/core-framework/Resources/views/Templates/tinyMCE.html.twig) from [here](https://github.com/uvdesk/core-framework/blob/master/Resources/views/Templates/tinyMCE.html.twig).
saved the file and hard refresh the site.

Before replacing  **tinyMCE.html.twig** : https://prnt.sc/xhblnt
After replacing **tinyMCE.html.twig** : https://prnt.sc/xhbvdx

**Comment by PeopleInside** [comment]
Followed the same steps:
- replaced /uvdesk/vendor/uvdesk/core-framework/Resources/views/Templates/tinyMCE.html.twig saved and hard refresh.

![SharedScreenshot](https://user-images.githubusercontent.com/5006150/105573265-8edaa400-5d5c-11eb-88ad-663a1d8480bc.jpg)

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Please verify if you are doing the changes for the project you are **running on browser**.
sometime it happens by mistake possibly running different one and made changes for other.
(remove complete code in of **tinyMCE.html.twig** file and check if your editor it is still running or not).

One more thing please send us the file (**tinyMCE.html.twig**) where you have made changes.

If still unable to do so create a ticket with your details we will check issue if any.

**Comment by PeopleInside** [comment]
I have just one uvdesk install so I cannot confuse.
[tinyMCE.html.twig.txt](https://github.com/uvdesk/support-center-bundle/files/5859919/tinyMCE.html.twig.txt)
I renamed the file .txt for upload here.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Have you cleared you cache by:

**php bin/console c:c --env prod**   (for production environment)
**php bin/console c:c --env dev**     (for dev environment)

**Comment by PeopleInside** [comment]
Umh I get the error: unable to write in /uvdesk/var/cache/prod" directory maybe this is the issue

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Yes, It may be please resolve it and try again.

**Comment by PeopleInside** [comment]
Done thanks. cache and prod folders seems must have 777 permission... is not dangerous?
works

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Did you try with 775 ?

**Comment by PeopleInside** [comment]
yes seems give error in console using commands you give

**Comment by papnoisanjeev** [comment]
@PeopleInside 

You can check this doc for symfony for file permission:  https://symfony.com/doc/current/setup/file_permissions.html

**Comment by PeopleInside** [comment]
Thanks seems the system create a new folder. I resolved.
Hope you can add also quote in the text editor as is difficult to reply to the customer without possibility to quote more sentences.
Thanks again

**Comment by papnoisanjeev** [comment]
@PeopleInside 
> Hope you can add also quote in the text editor as is difficult to reply to the customer without possibility to quote more sentences.

We have added this option as well.

Locate path:
**vendor/uvdesk/core-framework/Resources/views/Templates/tinyMCE.html.twig**

Open your **tinyMCE.html.twig** file and replace it from [here](https://github.com/uvdesk/core-framework/blob/master/Resources/views/Templates/tinyMCE.html.twig).

It will also reflect from next release.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

More ever you can update below files as well for **CSS style update** for **Block quote**.

**Check this:**  https://prnt.sc/xle8c4

Locate path in your project: 

**1.**  **vendor/uvdesk/core-framework/Resources/views/ticket.html.twig**

Open **ticket.html.twig** and replace your file from [here](https://github.com/uvdesk/core-framework/blob/master/Resources/views/ticket.html.twig).

**2.**  **vendor/uvdesk/support-center-bundle/Resources/views/Knowledgebase/ticketView.html.twig**

Open **ticketView.html.twig** and replace your file from [here](https://github.com/uvdesk/support-center-bundle/blob/master/Resources/views/Knowledgebase/ticketView.html.twig).

**Comment by PeopleInside** [comment]
Thank you. What will be showed quoted text in email?
Need to see if is clear also in emails. thanks I will apply the patch now

**Comment by papnoisanjeev** [comment]
> Thank you. What will be showed quoted text in email?
> Need to see if is clear also in emails. thanks I will apply the patch now

 It should add some space before the sentence as update is for website view.
