### ISSUE TITLE
back date should be disabled while creating broadcast message

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/support-center-bundle#119]
**Description**  
disable back date
![Screenshot_230](https://user-images.githubusercontent.com/43210406/105330591-7baec380-5bf8-11eb-887d-e7e1057ff950.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed in master branch [here](https://github.com/uvdesk/support-center-bundle/commit/3eb126277fd56a63bcddbc09b351442a052657a9).

**Comment by vaishaliwebkul** [comment]
@papnoisanjeev 
current date is not accepting, please verify this. https://prnt.sc/y04mrb

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

As we have again tested  we are able to select current date https://prnt.sc/y9totn
Please verify again and let us know exact issue.

**Comment by vaishaliwebkul** [comment]
@papnoisanjeev 
check this https://www.loom.com/share/f5adcde23d1f412284e4f87e4264975c

**Comment by vaishaliwebkul** [comment]
currently closing this as it's working
