### ISSUE TITLE
getting exception when sort category,article based on created date

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/support-center-bundle#120]
![Screenshot_231](https://user-images.githubusercontent.com/43210406/105354811-15856900-5c17-11eb-9cb6-ca0cdaf59daa.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed the issue in master [here](https://github.com/uvdesk/support-center-bundle/commit/8898090587a3760513feb00b9e171c02bdc2819b).

**Comment by vaishaliwebkul** [comment]
fixed

**Comment by vaishaliwebkul** [comment]
able to reproduce this issue again in updated https://github.com/uvdesk/support-center-bundle/

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed [here](https://github.com/uvdesk/support-center-bundle/commit/4910d53ed8ae3fa92b4881097ca597d5ef57814b).

**Comment by vaishaliwebkul** [comment]
working fine
