### ISSUE TITLE
duplicate editor options are visible in knowledgebase article editor

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/support-center-bundle#121]
![Screenshot_241](https://user-images.githubusercontent.com/43210406/106578636-bf44ee00-6565-11eb-941e-3844ffdc5b28.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed it [here](https://github.com/uvdesk/support-center-bundle).
Please verify.

**Comment by vaishaliwebkul** [comment]
fixed https://prnt.sc/ya2pe3
