### ISSUE TITLE
getting exception on marketing announcement when sort by Created At

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/support-center-bundle#130]
**Description**  
getting an exception on marketing announcement when sort by Created At

**How to reproduce**  

- Admin -> Marketing announcement 
- Filter status
- filter created At

**Additional context**  

![Screenshot_359](https://user-images.githubusercontent.com/43210406/116783005-f4e86d00-aaa9-11eb-8a87-c96de337b894.png)

**Comment by vipin-shrivastava** [comment]
@vaishaliwebkul 
we already fixed this issue. 
you have to run **php bin/console assets:install** command then clear your browser cache . Now, it will work fine .
