### ISSUE TITLE
When an agent logs in on the customer endpoint, redirect them

### ISSUE THREAD

**Issue by wmertens** [uvdesk/support-center-bundle#132]
An agent can't log in to the customer portal, this is confusing. Instead, they could just be redirected to their dashboard.

**Comment by papnoisanjeev** [comment]
@wmertens 

No, it is not possible as with **UVdesk** **agent** can also be a **customer** and they will have access as per role.
so redirection is not possible.

Both the panel are different and they should have to login from their respective panel.

Although if agent will access any routes related to admin panel without login then agent will redirected to admin/agent panel login.

**Comment by wmertens** [comment]
Oh, I had a look at the login query and it seemed to me that the role is a single non-bitfield integer, so an agent can't be a customer and vice versa?

**Comment by papnoisanjeev** [comment]
@wmertens 

Yes, if you want to add a customer as a agent.

**Comment by wmertens** [comment]
Ok, closing
