### ISSUE TITLE
customer is not able to add reply on ticket

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/support-center-bundle#135]
**Description**  
ACCESS DENIED ERROR MESSAGE IS COMING WHEN CUSTOMER TRY TO ADD REPLY FROM THEIR PANEL

![Screenshot_24](https://user-images.githubusercontent.com/43210406/126737315-0a9e3464-afa6-443b-9271-b483c0963a98.png)

![Screenshot_23](https://user-images.githubusercontent.com/43210406/126737283-465b66fb-b5c9-4dd5-8345-e9f8ab58bd19.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed [here](https://github.com/uvdesk/support-center-bundle/commit/1e29813c8e751c86d92484a2eb7e1b96cf31cc36).
