### ISSUE TITLE
When creating a ticket type from the admin side so admin side does not take alphabetic order of ticket type

### ISSUE THREAD

**Issue by komal-sh-27** [uvdesk/support-center-bundle#175]
**Description**  
When creating a ticket type from the admin side so admin side does not take alphabetic order of ticket type.

**How to reproduce**  
**Issue 1:**

Step 1: Go to the admin panel and **create a ticket type**:

![image](https://user-images.githubusercontent.com/63539748/154020966-bcb33d9f-0e1a-4094-946a-76f97d94b0d2.png)

Step 2: Now check the **admin side and also the customer side** of the ticket type option:

=> From admin side:
![Screenshot from 2022-02-15 13-53-22](https://user-images.githubusercontent.com/63539748/154021911-7dea088f-fc04-4348-a3e2-691ef7c71366.png)

=> From customer side:
![Screenshot from 2022-02-15 13-56-29](https://user-images.githubusercontent.com/63539748/154022275-861bfbc5-037c-4f14-864d-508a5b3463c8.png)

=> Also not showing these places sorted order of ticket type:
**On Workflow 
On prepared responses (Here also showing disable ticket type)
On the ticket view page
On the ticket list page**

**Issue 2:**
Step 3: Now also creating in starting to give space and save because **when used space in starting so alphabetic order ignore on the customer side and admin side**:

![Screenshot from 2022-02-15 13-56-29](https://user-images.githubusercontent.com/63539748/154022824-11da3f63-e356-4c22-9510-a88bc2443a7d.png)

**Possible Solution**  

- If we create ticket type from the admin side should be sorted order in alphabetic of ticket type on the admin side:

![Screenshot from 2022-02-15 14-05-30](https://user-images.githubusercontent.com/63539748/154023708-87c1d20b-f706-43df-8634-72d4825a7b02.png)

- If we leave a space in starting so it is should be sorted order in alphabetic of ticket type:

![Screenshot from 2022-02-15 14-04-35](https://user-images.githubusercontent.com/63539748/154023584-554f0e1b-b34e-4ff5-8152-e834447da59c.png)

**Comment by Komal-sharma-2712** [comment]
I have checked **issue number 2** is not solved at this moment:

Now also creating in starting to give space and save because **when used space in starting so alphabetic order ignore on the customer side and admin side**:

![image](https://user-images.githubusercontent.com/63539748/168745532-512b1827-8486-4b4c-ac31-50afe675114b.png)
