### ISSUE TITLE
UVdesk Contack form 

### ISSUE THREAD

**Issue by Alagirigod** [uvdesk/support-center-bundle#204]
when I click the installed uvdesk dashboard Contact form page, Redirect to the same page, Kindly check and let us know.

https://support.nuvedalearning.com/en/

**Comment by Komal-sharma-2712** [comment]
@Alagirigod 

Firstly, you go to the **branding section -> knowledgebase option**
Here you will see this option:  **Login required To create tickets**. This option should be unchecked:

![image](https://user-images.githubusercontent.com/63539748/187202533-9e602c9d-e78a-4a1d-a8f6-72c6ec225c67.png)


Now check once again on the customer panel and click on the contact us button.

If you have still the same issue let us know.

This issue will be resolved in the next release.

**Comment by Komal-sharma-2712** [comment]
@Alagirigod 

We are closing this issue, if you have still any doubts so reply on the same thread.
