### ISSUE TITLE
On the error page, Home links should go to the customer dashboard instead of customer login page

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/support-center-bundle#211]
**Description**  
On the error page, Home links should go to the customer dashboard

**How to reproduce**  
Step 1: Go to the customer end, on the error page click on home and support links:

![image](https://user-images.githubusercontent.com/63539748/198530087-66d32cee-2bb0-4804-bfbc-eee3b9ca0d9e.png)

Step 2: Click on the **home option** and here go to the customer login page instead of the customer main dashboard:

![image](https://user-images.githubusercontent.com/63539748/198524092-d1df6292-47c3-432b-acf9-51a496948fc4.png)

After clicking on the **support option** and here go to the customer dashboard instead of the customer login page

**Possible Solution**  

If we click on the **home link** option so here should go to the **customer dashboard** instead of the customer login page

**Comment by DoritosXL** [comment]
Hi I would like to contribute, could you add me as a contributor?

**Comment by Komal-sharma-2712** [comment]
This issue has been resolved now in uvdesk-1.1.3 version. So we are closing this issue.
