### ISSUE TITLE
Customer can view other's customer's ticket just by passing ticket id in URL

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/support-center-bundle#24]
### **Test Scenario**
1. customer login to their panel  for ex:having  name : vaishali
2.  customer view their ticket and change the ticket id of other's customer in URL to access other's ticket

### Customer is able to access other's ticket

![screenshot 91](https://user-images.githubusercontent.com/43210406/50536924-e7d8ad80-0b7f-11e9-9a5f-09c2c808da3f.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 
Fixed it in master will reflect in next release.
https://github.com/uvdesk/support-center-bundle/blob/master/Controller/Ticket.php#L352

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed in latest release.
