### ISSUE TITLE
Some of the attachments are missing from customer panel and on their mail

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/support-center-bundle#25]
### Attachment added in ticket reply by admin : 

![screenshot 97](https://user-images.githubusercontent.com/43210406/50555676-88041300-0cf5-11e9-955c-6c45125ddbd0.png)

### Attachments shown by customer on same ticket :+1:  
1. Some attachment are missing with same ticket at customer panel : 
2. also same on customer email 

![screenshot 98](https://user-images.githubusercontent.com/43210406/50555682-a2d68780-0cf5-11e9-95a4-f067e9c79d72.png)

**Comment by papnoisanjeev** [comment]
fixed
