### ISSUE TITLE
CSS not loading

### ISSUE THREAD

**Issue by septers99** [uvdesk/support-center-bundle#250]
Hello, I installed uvdesk skeleton on ubuntu with apache and after the installation the css is not loading properly.

![image](https://github.com/uvdesk/support-center-bundle/assets/158582487/32473f03-a014-4c59-b275-8ff08d8200c3)

**Comment by nikssandroid** [comment]
Me too

**Comment by papnoisanjeev** [comment]
Open you console for checking error.
Right click => click on inspect.
![image](https://github.com/user-attachments/assets/4020d455-4a74-46c7-837c-29c9e4a81fbd)

Now check on console tab.
![image](https://github.com/user-attachments/assets/1d170320-ecb2-48e2-8490-2370a1a552b2)
