### ISSUE TITLE
Article are not visible on knowledgebase 

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/support-center-bundle#49]
**All popular article are not listed on knowledgebase**

**Layout theme:** popular article

![Screenshot](https://user-images.githubusercontent.com/43210406/56715605-ce262c00-6755-11e9-991f-a269bad567b1.png)

**Comment by papnoisanjeev** [comment]
Issue has been fixed.
https://github.com/uvdesk/core-framework/pull/131
https://github.com/uvdesk/support-center-bundle/pull/50
