### ISSUE TITLE
Getting exception when collaborator login to support panel

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/support-center-bundle#99]
**Description**  

collaborator added in ticket then collaborator receives an account creation email by which he set password and login to the support panel.

**Additional context**  

![Screenshot (6)](https://user-images.githubusercontent.com/43210406/75897216-3bb6e480-5e5e-11ea-95e8-721f7139357f.png)

![Screenshot (4)](https://user-images.githubusercontent.com/43210406/75897240-46717980-5e5e-11ea-831e-e64f98f62ea4.png)

**Comment by papnoisanjeev** [comment]
[Fixed](https://github.com/uvdesk/support-center-bundle/commit/a3faf0e79e1e87538d80158ee4ee774c56079c98)
